### ISSUE TITLE
FR: Use JSONs for Custom Dictionaries

### ISSUE THREAD

**Issue by chrisgrieser** [tadashi-aikawa/obsidian-various-complements-plugin#108]
I have encountered a few bugs with various plugins in Obsidian, which, as I could determine, was caused by having a large custom dictionary file (~3800 lines, ~425kb) in my vault:
- https://github.com/SkepticMystic/breadcrumbs/issues/361
- https://github.com/kometenstaub/metadata-extractor/issues/17 (this issue also includes more details)

it seems that Obsidian is simply having problems parsing large files, since it unsuccessfully searches for metadata in such a large file. the developer of the metadata extractor plugin suggested, that Various Complements should use JSON as a format for large custom dictionaries to avoid such problems, as well to increase performance Various complements as well as Obsidian in general.

**Comment by tadashi-aikawa** [comment]
Hi, @chrisgrieser.

I couldn't understand why using the JSON format could solve that problem. 🤔 

> the developer of the metadata extractor plugin suggested, that Various Complements should use JSON as a format for large custom dictionaries to avoid such problems

Could you tell me the link to the comment?

**Comment by kometenstaub** [comment]
Markdown files are scanned for metadata. It is not recommended to have content in markdown files that isn't markdown, because it trips up the parser and can make Obsidian slow. That has happened with XML files that had the md extension in the past, for example.
A json file (or any other non-markdown file) isn't taken into account by the metadata cache, so it can be in the vault without stalling Obsidian.
So it's not primarily about the JSON format, but rather the extension.

Using JSON should also make it easier to create data/have easier compatibility.

**Comment by kometenstaub** [comment]
Plugins that use JSON are e.g. Obsidian Wordnet and Linked Data Vocabularies.

**Comment by tadashi-aikawa** [comment]
@kometenstaub 
Thank you for your explanation!

> A JSON file (or any other non-markdown file) isn't taken into account by the metadata cache, so it can be in the vault without stalling Obsidian.

Good. I have the same understanding as you :)

> Additionally, using the JSON format should also make it easier to create data/have easier compatibility and can be very easily read and worked with in JavaScript.

I adopted the textbase format because I gave priority to human readability, JSON is a little redundant for humans, and some IME dictionary format supports the same. (Of course, it is better to support both formats) 

@chrisgrieser
So, can you resolve the problem by using other extensions instead of `.md` ? (ex: `.csv`, `.txt`, ...)

**Comment by kometenstaub** [comment]
Yes, other extensions should work fine. `txt` seems to be a good candidate if you want to keep your format and parsing.

**Comment by chrisgrieser** [comment]
yeah, txt would work!

I just tested adding a .txt as a custom dictionary, and it does seem to be recognized (number of items in the status bar increases), but the editor suggester does not appear for them.

**Comment by tadashi-aikawa** [comment]
It works.

![image](https://user-images.githubusercontent.com/9500018/161279413-b5fa72f3-9075-4f84-9d72-394212eb0537.png)
![image](https://user-images.githubusercontent.com/9500018/161279462-4bcd1e9e-7876-415c-8f35-fcb301c6ffc8.png)

**Comment by chrisgrieser** [comment]
ah, my bad, haven't properly refresh the custom dictionaries 🙈 

works!

**Comment by tadashi-aikawa** [comment]
Related to #118

**Comment by tadashi-aikawa** [comment]
@chrisgrieser 
I have released [v6.1.0-beta4](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/6.1.0-beta4) 🚀 If you share custom dictionaries with anyone, the new JSON format will be helpful :)

**Comment by chrisgrieser** [comment]
by now I do not have the need for json custom dictionaries, since your other suggested solutions works just fine for me, sorry! 😅

**Comment by tadashi-aikawa** [comment]
Sure! I know 👍  That is merely sharing information 😄

**Comment by tadashi-aikawa** [comment]
Released [v6.1.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/6.1.0) 🚀
