### ISSUE TITLE
[Not issue] My new video introduced Various Complements plugin

### ISSUE THREAD

**Issue by emisjerry** [tadashi-aikawa/obsidian-various-complements-plugin#109]
Hi, i just want to let you know that i've made an introducing video about your helpful plugin. Maybe you will be intrested in: 

https://youtu.be/tiidkQhKjLY

This video was in Chinese with English/Japanese subtitles.

**Comment by tadashi-aikawa** [comment]
Hi, @emisjerry :)

Thank you for making an exciting video! I enjoyed watching until the end.😄 

Can I introduce your video(link) on an official document of Various Complements? Because It is helpful for many users.

---

P.S.

![image](https://user-images.githubusercontent.com/9500018/161409869-57125fcb-52bc-404c-98f4-eae14a8c97df.png)

If you want to show popup just after Chinese, It would be good that you use [English only](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/2.%20Strategies/english-only/) as a strategy instead of Default.

<`English only` strategy example>

https://user-images.githubusercontent.com/9500018/161410023-b8e93b43-da65-47bf-9436-6fffcce24fc0.mp4


Have a nice day!

**Comment by emisjerry** [comment]
Please go ahead. I'll try the English only strategy. Thanks for your work.

**Comment by tadashi-aikawa** [comment]
Added [📽️Videos](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/6.%20Showcase/%F0%9F%93%BD%EF%B8%8FVideos/) 👍
