### ISSUE TITLE
Add some keys to "Select a suggestion key"

### ISSUE THREAD

**Issue by tadashi-aikawa** [tadashi-aikawa/obsidian-various-complements-plugin#128]
I'm only throwing out ideas here - some may be bad ideas

For trigger keys I would consider options of
- None (mouse use only)
- Shift space (if possible - that might be intuitive - space would simply exit the list shift space selects)
- `

_Originally posted by @aubreyz in https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/discussions/124#discussioncomment-2721884_

**Comment by Glint-Eye** [comment]
if there would be an option for "right / left arrow" for Cycling through selection, then shift + right for adding selection.
+1 for shoft + space too

**Comment by tadashi-aikawa** [comment]
> if there would be an option for "right / left arrow" for Cycling through selection

Could you create another new issue?

> then shift + right for adding selection.

Does it mean adding a `shift + right` option to "Select a suggestion key" ?

**Comment by tadashi-aikawa** [comment]
@aubreyz
Added in [v7.0.0-beta8](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/discussions/133) 🚀

**Comment by aubreyz** [comment]
I haven't tested every one, but the shift-space works great and is nearly seamless. 

I am not sure what happens though if I select an item lower down on the list via the keyboard - it might be intuitive if I pressed down down and then shift-space (or whichever one was selected), or in that context a simple enter might be good as well because if someone is navigating in the suggestion list it is obvious they want to make a choice so enter would be fine here.

**Comment by tadashi-aikawa** [comment]
Thank you for your confirming :)

> it might be intuitive if I pressed down down and then shift-space (or whichever one was selected), or in that context a simple enter might be good as well because if someone is navigating in the suggestion list it is obvious they want to make a choice so enter would be fine here.

I see. I agree with the opinion, but it seems a bit complicated. 🤔

**Comment by tadashi-aikawa** [comment]
Released in [v7.0.0](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/releases/tag/7.0.0) 🚀
