### ISSUE TITLE
Complete with keywords

### ISSUE THREAD

**Issue by lbgws2** [tadashi-aikawa/obsidian-various-complements-plugin#143]
I suggest the plug-in has built-in keywords to complete with markdown syntax 

For example, during the input process, you can enter ;h2, and then pop-up a list will Heading level 2 in this document

The keyword list 
;h1-;h6    ---->   Heading level 1-Heading level 6
;bt       ---->      **bold text**
;it        ---->      _Italic text_
;bi        ---->      Bold and Italic
;bq      ---->      Blockquotes
;un      ---->      under lines
;sup      ---->      super script
;sub      ---->      sub script
;bc      ---->      backticks in code
;bd      ---->      code
;ol       ---->     Ordered Lists
;ul       ---->     Unordered Lists
;hr       ---->     horizontal rule
;ln       ---->     Links
;im       ---->    Images

There may be more advanced use cases

Customize a keyword list. After entering keywords, all rows containing keywords will be listed

**Comment by tadashi-aikawa** [comment]
Hi, @lbgws2. Thank you for your nice suggestion :)

However, I will not include them out of the box because the keyword depends on who uses it.

Instead, we are welcome to add to [📓Custom dictionary examples](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/6.%20Showcase/%F0%9F%93%93Custom%20dictionary%20examples/). Anyone who wants to use the keyword list can use and customize it :)

**Comment by lbgws2** [comment]
Maybe I didn't make myself clear

I mean using the markdown hierarchy to quickly get relevant content

For example, when I input H3, I can quickly list the contents of all H3 titles in the completion list. The purpose of generating this list is not to complete, but to quickly obtain information by using the markdown syntax,

For another example, if I am reading an article when I type; BT (means:bold text), I can quickly browse the marked key contents in the list

This is just an idea. Maybe a text jump plug-in is more suitable for it,

When reading or editing a long document,

Through the markdown syntax, I can list the structured contents of the document. After clicking on the list, I can quickly move to the corresponding position. Maybe this is what I want

**Comment by tadashi-aikawa** [comment]
Thank you for your description :)

> This is just an idea. Maybe a text jump plug-in is more suitable for it,

As you said, I'll not implement the feature now because Various Complements is a plugin for auto-complete.

> Through the markdown syntax, I can list the structured contents of the document. After clicking on the list, I can quickly move to the corresponding position. Maybe this is what I want

Although there is a limit that only supports headers, [Another Quick Switcher > Header floating search in file](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher#3%E2%83%A3-header-floating-search-in-file--header-search-in-file) has such a feature. If you don't have already tried it, please try it :)

Best regards.

**Comment by tadashi-aikawa** [comment]
This issue will be closed for now, as there have been no comments from visitors for a month.
