### ISSUE TITLE
No suggestion but a placeholder in iPadOS and iOS

### ISSUE THREAD

**Issue by StofvS** [tadashi-aikawa/obsidian-various-complements-plugin#147]
Since 15.3 Various Complements stopped giving suggestions but shows a placeholder. On my Mac your highly appreciated plugin functions as before.
![1EB93094-204C-4552-A515-B5F9D9DB76BC](https://user-images.githubusercontent.com/78209582/176880228-b0c8aad2-5506-4709-8594-02c3df7c9853.jpeg)

**Comment by tadashi-aikawa** [comment]
@StofvS 
What is your plugin version?

**Comment by StofvS** [comment]
7.0.1

**Comment by tadashi-aikawa** [comment]
> No suggestion but a placeholder in iPadOS and iOS
> Since 15.3 Various Complements stopped giving suggestions but shows a placeholder.

- Do you use *Obsidian mobile (insider version)* ?
- If so, what 15.3 do you mean?

**Comment by tadashi-aikawa** [comment]
I could reproduce it on Various Complements v7.0.1. But it doesn't install v7.0.1 in the latest mobile version. It installs v7.0.0 because v7.0.1 doesn't support the latest mobile version yet.

However, if you use BRAT to install it, it seems to install v7.0.1 heedless of the above dependencies (written in `versions.json`).

So please install and use v7.0.0 until Obsidian mobile updates the version comparable to Obsidian v0.15.x.

**Comment by StofvS** [comment]
Thanks for solving the puzzle!
Happy to know where I am with my workflow — it developed from nothing, but it fits me, so happy I don't really have to readjust.

It me took some time to wrap my head around BRAT, but I got it working. Thanks also for this solution.
