### ISSUE TITLE
How to avoid trigger when input Non-English languages 

### ISSUE THREAD

**Issue by chenyukang** [tadashi-aikawa/obsidian-various-complements-plugin#29]
Thank you for this awesome plugin, I love it when input English words. 
But I have an issue when inputting Chinese.
Here, it will also suggest the English words:

![image](https://user-images.githubusercontent.com/230646/143372497-de4ab080-58f7-49f4-8ebb-21234183c021.png)

**Comment by tadashi-aikawa** [comment]
Hi, @chenyukang!

I understood what you bother to because I think so many times while inputting Japanese with IME. So I am trying to add a new option, `Disable suggestions during IME On`. Would it be possible to resolve your issue?

**Before** (current version)

https://user-images.githubusercontent.com/9500018/143461975-79777fa6-e030-4053-bbdd-7ee5e17eb565.mp4

**After** (The version I am trying to)

https://user-images.githubusercontent.com/9500018/143462206-8409f71b-1c4c-4546-a9f4-69c20b4ac08a.mp4


I don't know which works correctly with your IME, but it probably works :)

**Comment by chenyukang** [comment]
> Hi, @chenyukang!
> 
> I understood what you bother to because I think so many times while inputting Japanese with IME. So I am trying to add a new option, `Disable suggestions during IME On`. Would it be possible to resolve your issue?
> 
> **Before** (current version)
> 
>  2021-11-25_23h47_18.mp4 
> **After** (The version I am trying to)
> 
>  2021-11-25_23h49_01.mp4 
> I don't know which works correctly with your IME, but it probably works :)

Thanks for reply!
If you have pre-release version for testing, I would like to have a try. 😊

**Comment by chenyukang** [comment]
Btw, I guess most users in Windows use Microsoft Input.

**Comment by tadashi-aikawa** [comment]
@chenyukang 
I have uploaded pre-release version 🚀 

If you use [BRAT](https://github.com/TfTHacker/obsidian42-brat), you can install it from `tadashi-aikawa/obsidian-plugin-dev-sandbox`. It includes some breaking changes because it corresponds to v3.0.0. You can see what changes are at https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/28.

Best regards.

**Comment by chenyukang** [comment]
> @chenyukang I have uploaded pre-release version 🚀
> 
> If you use [BRAT](https://github.com/TfTHacker/obsidian42-brat), you can install it from `tadashi-aikawa/obsidian-plugin-dev-sandbox`. It includes some breaking changes because it corresponds to v3.0.0. You can see what changes are at #28.
> 
> Best regards.

Confirmed it works perfectly, and we can also complete links now, awesome!
Thanks for your contribution. 🙌

**Comment by chenyukang** [comment]
Btw, do you have any better English dictionary files to config my dictionary.

**Comment by chenyukang** [comment]
I tried this words for complete, but it seems too big, it will hang up the plugin.
https://raw.githubusercontent.com/dwyl/english-words/master/words.txt

**Comment by chenyukang** [comment]
The above dictionary works perfect.
But I found another improvement we may implement.

For instance, we have 'banana' in dictionary, 
![image](https://user-images.githubusercontent.com/230646/143553215-96838066-ca45-42c0-ad16-b9b62137afe0.png)
but if I will type this word in the beginning of a sentence, I will type "Ba", but it will not complete, I guess ignore uppercase will be better:

![image](https://user-images.githubusercontent.com/230646/143553428-24b1192a-781b-4e41-a9de-f12c1f5c9f80.png)

**Comment by tadashi-aikawa** [comment]
Thank you for your reply!

> Confirmed it works perfectly

Glad to hear that 😄 

> do you have any better English dictionary files to config my dictionary.

Sorry, I have no idea because I don't use the custom dictionary feature.. 😅 

> but if I will type this word in the beginning of a sentence, I will type "Ba", but it will not complete, I guess ignore uppercase will be better:

That is very interesting :) Would you create another issue?

**Comment by tadashi-aikawa** [comment]
Done 97d772877b224dbcf4d50b25482716acd6e44c1e
