### ISSUE TITLE
Plugin Collaboration

### ISSUE THREAD

**Issue by Yeboster** [tadashi-aikawa/obsidian-various-complements-plugin#6]
Hi @tadashi-aikawa!

I am the author of [Obsidian autocomplete](https://github.com/Yeboster/autocomplete-obsidian) plugin.

First, thanks for this plugin, I am really happy that we are working to improve the typing speed of Obsidian with an autocomplete! I also like how you structured the plugin using the `hint` addon of CodeMirror and the current file word tokenization.

I have started the obsidian-autocomplete plugin at the beginning of this year with an urgent need: having an autocomplete plugin that supports LaTeX. So I've taken inspiration from the `hint` addon and made my custom implementation of it to learn better how it works and also to make a plugin that integrates better with Obsidian. In February, I've stopped the development since I had the university exams and started again a week ago by adding more autocomplete features.

Since we are both working on the same concept (autocomplete), and I have just discovered your plugin today, I wanted to ask you if you'd like to merge this plugin into one, to provide a faster, more powerful autocomplete. I know that working on a personal plugin is easier than collaborating, but I think it could be fun and constructive to merge both personal ideas into one project. 

I'd like to hear from you what you think about this idea and I will accept whatever you choose.

Have a nice day!

**Comment by tadashi-aikawa** [comment]
Hi @Yeboster.

Thank you for your great suggestion! I agree with your opinion because I have developed my plugin to provide more efficiency with Obsidian users.😄 

So I don't mind as follows.

- **Who and what plugin** provides auto-complete features (It would be good to merge my implementation into your plugin or the new one)
- **How** implements (ex. whether it uses CodeMirror Hints add-on or not)

Meanwhile, I think It is important for us to provide not only English but also other languages. We can because many Obsidian users would use their native languages (ex. I use Japanese). Thus I want to provide it upcoming.

If you could agree with my opinion, I want to collaborate with your autocomplete plugin!

I await a favorable reply from you.😉

**Comment by Yeboster** [comment]
Thanks for your kind response, @tadashi-aikawa. I am sure this collaboration can bring the most featureful autocomplete plugin ever made on Obsidian! As you suggested,  I've just added you as a collaborator of the autocomplete plugin 😄 

I also agree with you that languages suggestions are a must, so I suggest this should be our focus:
1. Create a tokenizer for current file; since you've already done it, we could take this logic and put it into a Provider (I need to think how to trigger the analyser inside the provider)
2. Tokenize custom file (so the user can use a custom file)
3. Add language specific files in the plugin (so the user can activate them like dictionaries)

This is just a possible roadmap, feel free to give suggestions and prioritize other aspects. Also, what do you think we could use to track the roadmap ? Create an MD file, Trello or something else ?

**Comment by tadashi-aikawa** [comment]
Hi @Yeboster.

Thank you, and I have accepted your collaborator request! It's the first time as a collaborator, so please let me know I do it incorrectly. 👍 

I almost agree with the roadmap you suggested. If I have to say something, 

1. [selectSuggestedTokens()](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/blob/main/main.ts#L21) might be use if prioritize sort logics are not implemented
2. Add [Use WebWorker to improve performance](https://github.com/obsidianmd/obsidian-releases/pull/155#issuecomment-774930410) (I think it to be a low priority because it is not a critical issue except for large text)

> what do you think we could use to track the roadmap ? Create an MD file, Trello or something else ?

I think it is enough to `Create an MD file` for now.

Best regards!

**Comment by Yeboster** [comment]
Hi @tadashi-aikawa,

Thanks for the suggestions! I agree that the sorting needs to be revised since right now it's very basic. I'll look into the roadmap tasks  in the following days. 
If you have time, you can take a look at the [source code](https://github.com/Yeboster/autocomplete-obsidian) and if you want to change something feel free to create a branch! I'm using [git flow](https://datasift.github.io/gitflow/IntroducingGitFlow.html) to manage the release lifecycle, but you can do as you like.

Lastly, how do you think we could track the development, and who's working on what task ? We might use GitHub issues or discord to have a faster way to communicate.

Have a nice day!

**Comment by tadashi-aikawa** [comment]
Hi @Yeboster.

Thank you for your agreement! As suggested, I would develop on a branch using git-flow if needed. (P.S. I like your source codes using functional programming😉)

> how do you think we could track the development, and who's working on what task?

I like using GitHub issues to track development and communicate. I have not had much time because of my job recently, so I hope you will understand my reply might be late.

Have a nice day!

**Comment by Yeboster** [comment]
Hello @tadashi-aikawa,

That's great! So feel free to create a branch and with an issue related, so we can have an idea on what we are working on. Thanks for the compliment! I'm just in love with FP, but I still need to learn a lot 😄 

No worries about the late replies, I am working too so the time left is not so much (and also I am from europe, so the time zone difference between us is huge). Anyway in the next days I will create an issue about the roadmap, including your suggestions.

Until then, have a nice day!

**Comment by tadashi-aikawa** [comment]
This issue will be closed because the collaboration has begun✨
