### ISSUE TITLE
Minimum number characters for trigger is 3 even when I set it to 0

### ISSUE THREAD

**Issue by ooker777** [tadashi-aikawa/obsidian-various-complements-plugin#98]
[⚙️Min number of characters for trigger](https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/4.%20Options/4.1.%20Main/%E2%9A%99%EF%B8%8FMin%20number%20of%20characters%20for%20trigger/ "⚙️Min number of characters for trigger - Various Complements")

I can't even use two-character aliases, like `hh`, but have to use three-character aliases, like `hhh`,` to trigger suggestions

**Comment by tadashi-aikawa** [comment]
Please read https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/4.%20Options/4.1.%20Main/%E2%9A%99%EF%B8%8FMin%20number%20of%20characters%20for%20trigger/#notes

**Comment by ooker777** [comment]
I can't believe it is right there

**Comment by tadashi-aikawa** [comment]
It writes in the description of a setting, too. 

![image](https://user-images.githubusercontent.com/9500018/156466369-c7b9103c-f328-45e6-b15f-aeb7e17824a9.png)

Since it is not intuitive and unkind, it may be better to divide the setting to `Specify Min number of characters for trigger` and `Min number of characters for trigger`

**Comment by tadashi-aikawa** [comment]
Moved it to `Definitions`

![image](https://user-images.githubusercontent.com/9500018/156473429-3446d887-9698-4478-b976-69110e105472.png)
